name = "stun-redirect"
main = "./worker.js"
compatibility_date = "2025-07-05"
workers_dev = true

[[routes]]
pattern = "stun.example.com"
custom_domain = true

[vars]
DOMAIN = "example.com"
SUBDOMAINS = "openwrt,portainer"
BEARER_TOKEN = ""

[[d1_databases]]
binding = "LUCKY"
database_name = "lucky"
database_id = ""
